server:
  port: 8081
spring:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cliente
    username: root
    password:
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8090/eureka/



eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}